import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { poppins } from "./fonts";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={`${poppins.className} h-[50rem] w-full dark:bg-black bg-white  dark:bg-grid-white/[0.08] bg-grid-black/[0.08]`}
        className={`${poppins.className} h-[50rem] w-full bg-customGray`}
      >
        {children}
      </body>
    </html>
  );
}
